name: flutter_paypal_payment
description: This package simplifies integrating PayPal payments into your mobile app. Key features include seamless in-app PayPal integration
version: 1.0.6
homepage: https://github.com/tharwatsamy/flutter_paypal_payment_checkout

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

